### PR TITLE
Move arrow to Suggests

### PR DESCRIPTION
**Pull request by thisisnic**
Related to https://github.com/apache/arrow/issues/39806. Since it's not clear that we'll be able to resolve everything with CRAN before February 9, this PR moves arrow from Imports to Suggests. When submitted to CRAN, this will prevent your checks failing on CRAN due to arrow's potential archival, but if we don’t get removed, or when we do get back on CRAN, you can revert this.

I've tested this locally by uninstalling arrow and running `devtools::check(".", env_vars = c(NOT_CRAN="false"))`, though if I had more time to look at this, I might have gone through the tests and only skipped the ones which definitely require arrow and not all of them.

### CODE REVIEW

**Comment by nbc** [comment]
Thank you very much for the work  @thisisnic! 
I will look at this shortly.

**Comment by ddotta** [comment]
Wow great work !!! Unfortunately, I'm very booked up this month and I'm afraid I won't have enough time to review the PR properly 😞

**Comment by ddotta** [comment]
@nbc I think we can close this PR now that arrow is back on CRAN ?

**Comment by nbc** [comment]
Yes @ddotta we can close !

**Pull request closed without merging**
